# Generated by Django 5.1.7 on 2025-03-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('RENT', 'Rent'), ('GROCERIES', 'Groceries'), ('TRANSPORTATION', 'Transportation'), ('UTILITIES', 'Utilities'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('DEBT', 'Debt Repayment'), ('SAVINGS', 'Savings & Investments'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('RENT', 'Rent'), ('GROCERIES', 'Groceries'), ('TRANSPORTATION', 'Transportation'), ('UTILITIES', 'Utilities'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('DEBT', 'Debt Repayment'), ('SAVINGS', 'Savings & Investments'), ('EDUCATION', 'Education'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
