# Generated by Django 5.1.7 on 2025-04-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('RENT', 'Rent'), ('FOOD', 'Food'), ('GROCERIES', 'Groceries'), ('TRANSPORTATION', 'Transportation'), ('UTILITIES', 'Utilities'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('DEBT', 'Debt Repayment'), ('SAVINGS', 'Savings & Investments'), ('EDUCATION', 'Education'), ('OTHER', 'Other'), ('RENT', 'Rent')], default='FOOD', max_length=20),
        ),
    ]
